name: stockin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  curved_navigation_bar: ^1.0.3
  floating_navbar: ^2.0.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.5
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  fonts:
    - family: LilitaOne
      fonts:
        - asset: lib/assets/LilitaOne-Regular.ttf
